management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
user:
  firstName: abisekk shanmugam   
  endpoints:
    web:
      exposure:
        include:
        - "*"
